format = """
[░▒▓](#ffffff)\
[  ](fg:#333333 bg:#ffffff)\
[](fg:#ffffff bg:#db4740)\
$directory\
[](fg:#db4740 bg:#394260)\
$git_branch\
$git_status\
[](fg:#394260 bg:#212736)\
$time\
[ ](fg:#1d2230)\
\n$character"""

[directory]
style = "fg:#ffffff bg:#db4740"
format = "[ $path ]($style)"
truncation_length = 3
truncation_symbol = "…/"

[directory.substitutions]
"Documents" = "󰈙 "
"Downloads" = " "
"Music" = " "
"Pictures" = " "

[git_branch]
symbol = ""
style = "bg:#394260"
format = '[[ $symbol $branch ](fg:#db4740 bg:#394260)]($style)'

[git_status]
style = "bg:#394260"
format = '[[($all_status$ahead_behind )](fg:#db4740 bg:#394260)]($style)'

[time]
disabled = false
time_format = "%R" # Hour:Minute Format
style = "bg:#1d2230"
format = '[[  $time ](fg:#a0a9cb bg:#1d2230)]($style)'

[character]
disabled = false
success_symbol = '[](bold fg:#db4740)'
error_symbol = '[](bold fg:db4740)'
vimcmd_symbol = '[](bold fg:#db4740)'